[project]
name = "agentic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.4.247",
    "logfire>=3.2.0",
    "pydantic-ai>=0.0.19",
    "streamlit>=1.41.1",
    "supabase>=2.11.0",
]
